server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://erhrbtuzgfewhj:bed6f7a175a15166442494136e6cb5ccd7f6a934df30183945bb97ab0043bf2f@ec2-54-90-211-192.compute-1.amazonaws.com:5432/dad1u9sk1gf07g
    username: erhrbtuzgfewhj
    password: bed6f7a175a15166442494136e6cb5ccd7f6a934df30183945bb97ab0043bf2f
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO -Santander Dev Week
